# rEFInd KorvNN Theme
# https://github.com/KorvNN/rEFInd-KorvNN-theme

# --- BASIC SETTINGS ---
resolution 1920 1080
hideui hints
showtools firmware

# --- ICONS & BACKGROUND ---
icons_dir themes/rEFInd-KorvNN/icons
banner themes/rEFInd-KorvNN/background.korvnn.png
banner_scale fillscreen

# --- ICON SIZES ---
big_icon_size 128
small_icon_size 48

# --- SELECTION HIGHLIGHTS ---
selection_small themes/rEFInd-KorvNN/selection_small.png
selection_big themes/rEFInd-KorvNN/selection_big.png
